2021-02-10 17:39:37 INFO  [main]: Приложение успешно запущено
2021-02-10 17:39:45 ERROR [main]: log4jhw.exception.MyException: Сгенерированное число – 1
2021-02-10 17:39:45 INFO  [main]: Приложение успешно запущено
2021-02-10 17:39:49 INFO  [main]: Приложение успешно запущено
2021-02-10 17:39:53 ERROR [main]: log4jhw.exception.MyException: Сгенерированное число – 2
2021-02-10 17:39:53 INFO  [main]: Приложение успешно запущено
2021-02-10 17:40:12 INFO  [main]: Приложение успешно запущено
2021-02-10 17:40:16 INFO  [main]: Приложение успешно запущено
2021-02-10 17:40:19 INFO  [main]: Приложение успешно запущено
2021-02-10 17:40:23 INFO  [main]: Приложение успешно запущено
2021-02-10 17:40:26 ERROR [main]: log4jhw.exception.MyException: Сгенерированное число – 1
2021-02-10 17:40:40 INFO  [main]: Приложение успешно запущено
2021-02-10 17:40:49 ERROR [main]: log4jhw.exception.MyException: Сгенерированное число – 5
2021-02-10 17:40:49 ERROR [main]: log4jhw.exception.MyException: Сгенерированное число – 3
2021-02-10 17:40:49 INFO  [main]: Приложение успешно запущено
2021-02-10 17:40:49 ERROR [main]: log4jhw.exception.MyException: Сгенерированное число – 5
2021-02-10 17:40:49 ERROR [main]: log4jhw.exception.MyException: Сгенерированное число – 0
2021-02-10 17:40:49 ERROR [main]: log4jhw.exception.MyException: Сгенерированное число – 0
2021-02-10 17:40:49 INFO  [main]: Приложение успешно запущено
2021-02-10 17:40:49 INFO  [main]: Приложение успешно запущено
